
Root:
    img: img
    plot: plot
    photos: photos
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            size_hint_y: None
            height: 50
            Button:
                text: 'Load'
                on_release: root.show_load()
            Slider:
                id: slid
                step: 1
                on_value: root.slider_changed_value(slid.value)
            Button:
                text: 'Run segmentation A'
                on_release:root.lung_segment_watershed()
            Button:
                text: 'Run segmentation B'
                on_release:root.lung_segment_binary()
            # Button:
            #    text: 'Save'
            #    on_release: root.show_save()
        BoxLayout:
            id: photos
            Image:
                id: img
                source: '3.jpg'
            MyFigure:
                id: plot
        
            

<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)

<SaveDialog>:
    text_input: text_input
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser
            on_selection: text_input.text = self.selection and self.selection[0] or ''

        TextInput:
            id: text_input
            size_hint_y: None
            height: 30
            multiline: False

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Save"
                on_release: root.save(filechooser.path, text_input.text)

