
RootWidget:
    id: root_widget
    img: img
    plot: plot
    dicom_viewer: dicom_viewer
    slide_number: slide_number
    StackLayout:
        orientation: 'lr-tb'
        StackLayout:
            id: menu_panel
            orientation: 'tb-lr'
            width: root_widget.width * 0.2
            size_hint_x: None
            Button:
                id: button_load_image
                text: 'Load'
                size_hint_max_y: 50
                on_release: root.show_load()
            Button:
                id: button_anonymize
                text: 'Anonymize'
                size_hint_max_y: 50
                disabled: True
        BoxLayout:
            id: images_panel
            orientation: 'horizontal'
            width: root_widget.width * 0.8
            size_hint_x: None
            BoxLayout:
                id: simple_image
                Image:
                    id: img
                    source: '3.jpg'
            BoxLayout:
                id: dicom_viewer
                orientation: 'vertical'
                BoxLayout:
                    size_hint_max_y: 50
                    orientation: 'horizontal'
                    Button:
                        id: button_prev
                        text: 'Previous'
                        on_press: root.slider_changed_value(-1)
                    Label:
                        id: slide_number
                    Button:
                        id: button_next
                        text: 'Next'
                        on_press: root.slider_changed_value(1)


                # Slider:
                #    height: 50
                #    size_hint_y: None
                #    id: slid
                #    step: 1
                #    on_value: root.slider_changed_value(slid.value)
                # Button:
                #    text: 'Save'
                #    on_release: root.show_save()
                MyFigure:
                    id: plot



<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)

<SaveDialog>:
    text_input: text_input
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser
            on_selection: text_input.text = self.selection and self.selection[0] or ''

        TextInput:
            id: text_input
            size_hint_y: None
            height: 30
            multiline: False

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Save"
                on_release: root.save(filechooser.path, text_input.text)

