#:import path pathlib
# it means: import pathlib as path

RootWidget:
    id: root_widget
    plot: plot.__self__
    left_panel: left_panel.__self__
    menu_panel: menu_panel.__self__
    slider: slider.__self__
    net_label: net_result.__self__
    slices_info: slices_info.__self__
    # dd_btn: btn_dropout
    BoxLayout:
        orientation: 'horizontal'
        id: whole_panel
        BoxLayout:
            width: root_widget.width * 0.2
            id: menu_panel
            orientation: 'vertical'
            size_hint_x: None
            Button:
                id: button_load_image
                text: 'Load'
                size_hint_max_y: 50
                on_release: root.show_load()
            Button:
                id: button_anonymize
                text: 'Save anonymized\nimage'
                text_size: self.size
                halign: 'center'
                valign: 'middle'
                size_hint_max_y: 50
                on_release: root.show_save()
            Button:
                id: button_segmentation_A
                text: 'Segmentation\nWatershed'
                text_size: self.size
                halign: 'center'
                valign: 'middle'
                size_hint_max_y: 50
                on_release: root.lung_segment_watershed()
            Button:
                id: button_segmentation_binary
                text: 'Segmentation\nBinary'
                size_hint_max_y: 50
                text_size: self.size
                halign: 'center'
                valign: 'middle'
                on_release: root.lung_segment_binary()
            Button:
                id: button_segmentation_KMeansBinary
                text: 'Segmentation\nKMeans'
                text_size: self.size
                halign: 'center'
                valign: 'middle'
                size_hint_max_y: 50
                on_release: root.lung_segment_kmeans()
            Button:
                id: button_layers
                text: 'Automatic\nlayer choice'
                size_hint_max_y: 50
                text_size: self.size
                halign: 'center'
                valign: 'middle'
                on_release: root.automatic_layer_choice()
            Button:
                id: button_net
                text: 'Neural\nNetwork'
                size_hint_max_y: 50
                text_size: self.size
                halign: 'center'
                valign: 'middle'
                on_release: root.neural_network()
            Button:
                id: button_net
                text: 'GLCM'
                size_hint_max_y: 50
                text_size: self.size
                halign: 'center'
                valign: 'middle'
                on_release: root.glcm()
            Button:
                id: button_net
                text: 'Alexnet'
                size_hint_max_y: 50
                text_size: self.size
                halign: 'center'
                valign: 'middle'
                on_release: root.alexnet()
            Button:
                id: button_result
                text: 'Show Result'
                size_hint_max_y: 50
                text_size: self.size
                halign: 'center'
                valign: 'middle'
                on_release: root.show_result_popup()
            Button:
                id: button_net
                text: 'Haralick'
                size_hint_max_y: 50
                text_size: self.size
                halign: 'center'
                valign: 'middle'
                on_release: root.haralick()
            Label:
                id: net_result
                text: ''
                size_hint_max_y: 50
            Button:
                text: 'Draw lesions'
                on_release: root.draw_lesions()
            Button:
                text: 'Analize drawn'
                on_release: root.analize_drawn()

        BoxLayout:
            orientation: 'vertical'
            id: left_panel
            BoxLayout:
                orientation: 'horizontal'
                size_hint_max_y: 50
                Button:
                    text: "Prev"
                    id: button_prev
                    size_hint_max_x: 40
                    on_release: root.load_next_slice(-1)
                Slider:
                    id: slider
                    step: 1
                    range: (0, 0)
                    on_value: root.slider_changed_value(slider.value)
                Button:
                    text: "Next"
                    id: button_next
                    size_hint_max_x: 40
                    on_release: root.load_next_slice(1)
            Label:
                id: slices_info
                text: 'Slice: 1/1'
                size_hint_max_y: 50
                size: self.size
            MyFigure:
                id: plot


<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserIconView:
            id: filechooser
            path: str(path.Path().resolve().parent.parent / "images_data")

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)

<SaveDialog>:
    text_input: text_input
    BoxLayout:
        id: save
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserIconView:
            id: filechooser
            on_selection: text_input.text = self.selection and self.selection[0] or ''
            path: str(path.Path().resolve().parent.parent / "images_data")

        TextInput:
            id: text_input
            size_hint_y: None
            height: 30
            multiline: False

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: save.dismiss()

            Button:
                text: "Save"
                on_release: root.save(filechooser.path, text_input.text)

<ResultPopup@Popup>:
    id: result_popup
    auto_dismiss: False
    title: 'Result popup'
    size_hint: (.8, .8)
    BoxLayout:
        orientation: 'vertical'
        padding: [5, 5, 5, 5]
        BoxLayout:
            size_hint_max_y: 50
            Button:
                text: 'Generate report'
                on_release: result_popup.show_save()
            Button:
                text: 'Close me'
                on_release: result_popup.dismiss()

<CustomDropDown>:
    Button:
        text: 'My first Item'
        size_hint_y: None
        height: 44
        on_release: root.select('item1')
    Label:
        text: 'Unselectable item'
        size_hint_y: None
        height: 44
    Button:
        text: 'My second Item'
        size_hint_y: None
        height: 44
        on_release: root.select('item2')

<DrawDialog@Popup>:
    id: draw_dialog
    title: 'Draw dialog'
    draw_panel: draw_panel.__self__
    popup_content: popup_content.__self__
    add_region_button: add_region_button.__self__
    BoxLayout:
        id: popup_content
        orientation: 'horizontal'
        RelativeLayout:
            id: draw_panel
            width: draw_dialog.width*0.8
            padding: 0
            margin: 0
            spacing: 0
        BoxLayout:
            size_hint_max_x: 100
            orientation: "vertical"
            Button:
                id: add_region_button
                text: 'Add region'
                size_hint_max_y: 50
            Button:
                id: delete_region_button
                text: 'Delete region'
                size_hint_max_y: 50
            Button:
                text: 'Done'
                id: done_region_button
                on_release: draw_dialog.dismiss()
                size_hint_max_y: 50
