RootWidget:
    id: root_widget
    plot: plot.__self__
    left_panel: left_panel.__self__
    menu_panel: menu_panel.__self__
    slid: slid.__self__
    net_label: net_result.__self__
    BoxLayout:
        orientation: 'horizontal'
        id: whole_panel
        StackLayout:
            width: root_widget.width * 0.2
            id: menu_panel
            orientation: 'tb-lr'
            size_hint_x: None
            Button:
                id: button_load_image
                text: 'Load'
                size_hint_max_y: 50
                on_release: root.show_load()
            Button:
                id: button_segmentation_A
                text: 'Segmentation\nWatershed'
                size_hint_max_y: 50
                on_release: root.lung_segment_watershed()
            Button:
                id: button_segmentation_binary
                text: 'Segmentation\nBinary'
                size_hint_max_y: 50
                on_release: root.lung_segment_binary()
            Button:
                id: button_layers
                text: 'Automatic\nlayer choice'
                size_hint_max_y: 50
                on_release: root.automatic_layer_choice()
            Button:
                id: button_net
                text: 'Neural\nNetwork'
                size_hint_max_y: 50
                on_release: root.neural_network()
            Label:
                id: net_result
                text: ''
                size_hint_max_y: 50
            Button:
                id: button_anonymize
                text: 'Save anonymized\nimage'
                size_hint_max_y: 50
                on_release: root.show_save()
        BoxLayout:
            orientation: 'vertical'
            id: left_panel
            BoxLayout:
                orientation: 'horizontal'
                size_hint_max_y: 50
                Button:
                    text: "Prev"
                    id: button_prev
                    size_hint_max_x: 40
                    on_release: root.load_next_slice(-1)
                Slider:
                    id: slid
                    step: 1
                    on_value: root.slider_changed_value(slid.value)
                Button:
                    text: "Next"
                    id: button_next
                    size_hint_max_x: 40
                    on_release: root.load_next_slice(1)
            MyFigure:
                id: plot


<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser
            path: r"C:\Users\Maya\studia\4rok\inz\covidSeg"

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)

<SaveDialog>:
    text_input: text_input
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser
            on_selection: text_input.text = self.selection and self.selection[0] or ''

        TextInput:
            id: text_input
            size_hint_y: None
            height: 30
            multiline: False

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Save"
                on_release: root.save(filechooser.path, text_input.text)